packages:
  - "apps/*"
  - "packages/*"
  - "tools/*"
  - "examples/*"
  - "!**/node_modules/**"
  - "!**/dist/**"
  - "!**/.turbo/**"
  - "!**/coverage/**"
allowBuilds:
  "@prisma/engines": true
  prisma: true
